create schema if not exists private;
revoke all on schema private from public;

create or replace function private.is_valid_cuit(value text)
returns boolean
language plpgsql
immutable
strict
set search_path = ''
as $$
declare
  digits text := regexp_replace(value, '[^0-9]', '', 'g');
  weights integer[] := array[5, 4, 3, 2, 7, 6, 5, 4, 3, 2];
  total integer := 0;
  verifier integer;
begin
  if length(digits) <> 11 or digits ~ '^(.)\1+$' then
    return false;
  end if;

  for digit_index in 1..10 loop
    total := total + substring(digits from digit_index for 1)::integer * weights[digit_index];
  end loop;

  verifier := 11 - (total % 11);
  if verifier = 11 then
    verifier := 0;
  elsif verifier = 10 then
    verifier := 9;
  end if;

  return verifier = right(digits, 1)::integer;
end;
$$;

create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null check (username ~ '^[a-z0-9][a-z0-9._-]{2,31}$'),
  display_name text not null check (length(btrim(display_name)) between 2 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index profiles_username_unique_idx on public.profiles (lower(username));

create table public.billing_entities (
  id bigint generated by default as identity primary key,
  name text not null check (length(btrim(name)) between 2 and 160),
  status text not null default 'active' check (status in ('active', 'inactive', 'archived')),
  legal_type text not null check (legal_type in ('srl', 'monotributista', 'llc')),
  country_code text not null check (country_code in ('AR', 'US')),
  fiscal_id_type text not null check (fiscal_id_type in ('CUIT', 'EIN')),
  fiscal_id text not null,
  fiscal_id_normalized text generated always as (regexp_replace(fiscal_id, '[^0-9]', '', 'g')) stored,
  fiscal_address text not null check (length(btrim(fiscal_address)) between 5 and 300),
  gross_income_number text,
  billing_email text check (billing_email is null or billing_email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'),
  default_voucher text not null check (default_voucher in ('A', 'B_EXEMPT', 'C', 'LLC')),
  allows_b_exempt boolean not null default false,
  point_of_sale text,
  invoice_prefix text,
  created_by uuid references auth.users(id) on delete restrict,
  updated_by uuid references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  archived_by uuid references auth.users(id) on delete restrict,
  constraint billing_entities_fiscal_fields_check check (
    (
      legal_type in ('srl', 'monotributista')
      and country_code = 'AR'
      and fiscal_id_type = 'CUIT'
      and private.is_valid_cuit(fiscal_id)
      and point_of_sale ~ '^[0-9]{4}$'
      and invoice_prefix is null
    )
    or
    (
      legal_type = 'llc'
      and country_code = 'US'
      and fiscal_id_type = 'EIN'
      and fiscal_id ~ '^[0-9]{2}-?[0-9]{7}$'
      and point_of_sale is null
      and invoice_prefix ~ '^[A-Z0-9][A-Z0-9-]{1,11}$'
    )
  ),
  constraint billing_entities_voucher_check check (
    (legal_type = 'srl' and default_voucher = 'A')
    or (legal_type = 'srl' and allows_b_exempt and default_voucher = 'B_EXEMPT')
    or (legal_type = 'monotributista' and not allows_b_exempt and default_voucher = 'C')
    or (legal_type = 'llc' and not allows_b_exempt and default_voucher = 'LLC')
  ),
  constraint billing_entities_b_exempt_check check (not allows_b_exempt or legal_type = 'srl'),
  constraint billing_entities_archive_check check (
    (status = 'archived' and archived_at is not null and archived_by is not null)
    or (status <> 'archived' and archived_at is null and archived_by is null)
  )
);

create unique index billing_entities_active_fiscal_id_unique_idx
  on public.billing_entities (fiscal_id_type, fiscal_id_normalized)
  where status <> 'archived';
create index billing_entities_status_idx on public.billing_entities (status);
create index billing_entities_legal_type_idx on public.billing_entities (legal_type);

create table public.entity_bank_accounts (
  id bigint generated always as identity primary key,
  entity_id bigint not null references public.billing_entities(id) on delete restrict,
  bank_name text not null check (length(btrim(bank_name)) between 2 and 160),
  account_holder text not null check (length(btrim(account_holder)) between 2 and 160),
  currency text not null check (currency ~ '^[A-Z]{3}$'),
  account_scope text not null check (account_scope in ('local', 'international')),
  cbu text,
  alias text,
  account_number text,
  routing_number text,
  swift_bic text,
  iban text,
  is_primary boolean not null default false,
  created_by uuid references auth.users(id) on delete restrict,
  updated_by uuid references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  constraint entity_bank_accounts_details_check check (
    (
      account_scope = 'local'
      and regexp_replace(coalesce(cbu, ''), '[^0-9]', '', 'g') ~ '^[0-9]{22}$'
      and account_number is null
      and routing_number is null
      and swift_bic is null
      and iban is null
    )
    or
    (
      account_scope = 'international'
      and length(btrim(coalesce(account_number, ''))) >= 4
      and (
        length(btrim(coalesce(routing_number, ''))) >= 4
        or swift_bic ~ '^[A-Z0-9]{8}([A-Z0-9]{3})?$'
        or length(btrim(coalesce(iban, ''))) >= 10
      )
      and cbu is null
      and alias is null
    )
  )
);

create index entity_bank_accounts_entity_idx on public.entity_bank_accounts (entity_id);
create unique index entity_bank_accounts_primary_currency_idx
  on public.entity_bank_accounts (entity_id, currency)
  where is_primary and archived_at is null;

create table public.entity_arca_documents (
  id bigint generated always as identity primary key,
  entity_id bigint not null references public.billing_entities(id) on delete restrict,
  original_file_name text not null check (length(btrim(original_file_name)) between 5 and 255),
  storage_path text not null unique,
  expiration_date date not null,
  uploaded_by uuid not null references public.profiles(user_id) on delete restrict,
  uploaded_at timestamptz not null default now(),
  superseded_at timestamptz,
  revoked_at timestamptz,
  revoked_by uuid references public.profiles(user_id) on delete restrict,
  constraint entity_arca_documents_revoke_check check (
    (revoked_at is null and revoked_by is null)
    or (revoked_at is not null and revoked_by is not null)
  )
);

create index entity_arca_documents_entity_idx
  on public.entity_arca_documents (entity_id, uploaded_at desc);
create unique index entity_arca_documents_current_idx
  on public.entity_arca_documents (entity_id)
  where superseded_at is null and revoked_at is null;

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create or replace function private.set_entity_audit()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
begin
  if tg_op = 'INSERT' then
    new.created_by := coalesce(actor, new.created_by);
    new.updated_by := coalesce(actor, new.updated_by);
  else
    new.created_at := old.created_at;
    new.created_by := old.created_by;
    new.updated_by := coalesce(actor, new.updated_by, old.updated_by);
  end if;
  new.updated_at := now();
  return new;
end;
$$;

create or replace function private.set_account_audit()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
begin
  if tg_op = 'INSERT' then
    new.created_by := coalesce(actor, new.created_by);
    new.updated_by := coalesce(actor, new.updated_by);
  else
    new.created_at := old.created_at;
    new.created_by := old.created_by;
    new.updated_by := coalesce(actor, new.updated_by, old.updated_by);
  end if;
  new.updated_at := now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function private.set_updated_at();

create trigger billing_entities_set_audit
before insert or update on public.billing_entities
for each row execute function private.set_entity_audit();

create trigger entity_bank_accounts_set_audit
before insert or update on public.entity_bank_accounts
for each row execute function private.set_account_audit();

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  profile_username text;
begin
  profile_username := lower(coalesce(
    nullif(new.raw_user_meta_data ->> 'username', ''),
    split_part(coalesce(new.email, ''), '@', 1)
  ));

  insert into public.profiles (user_id, username, display_name)
  values (
    new.id,
    profile_username,
    coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), profile_username)
  )
  on conflict (user_id) do update
    set username = excluded.username,
        display_name = excluded.display_name;

  return new;
end;
$$;

create trigger on_auth_user_created
after insert or update of email, raw_user_meta_data on auth.users
for each row execute function private.handle_new_user();

create or replace function public.save_billing_entity(
  p_entity jsonb,
  p_accounts jsonb default '[]'::jsonb,
  p_expected_updated_at timestamptz default null
)
returns public.billing_entities
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  entity_id bigint := nullif(p_entity ->> 'id', '')::bigint;
  account jsonb;
  account_id bigint;
  current_updated_at timestamptz;
  saved_entity public.billing_entities;
begin
  if actor is null then
    raise exception using errcode = '42501', message = 'AUTH_REQUIRED';
  end if;
  if jsonb_typeof(p_entity) <> 'object' then
    raise exception using errcode = '22023', message = 'INVALID_ENTITY_PAYLOAD';
  end if;
  if jsonb_typeof(p_accounts) <> 'array' or jsonb_array_length(p_accounts) = 0 then
    raise exception using errcode = '23514', message = 'AT_LEAST_ONE_BANK_ACCOUNT_REQUIRED';
  end if;

  if entity_id is null then
    insert into public.billing_entities (
      name, status, legal_type, country_code, fiscal_id_type, fiscal_id,
      fiscal_address, gross_income_number, billing_email, default_voucher,
      allows_b_exempt, point_of_sale, invoice_prefix, created_by, updated_by
    ) values (
      btrim(p_entity ->> 'name'),
      coalesce(nullif(p_entity ->> 'status', ''), 'active'),
      p_entity ->> 'legalType',
      p_entity ->> 'countryCode',
      p_entity ->> 'fiscalIdType',
      btrim(p_entity ->> 'fiscalId'),
      btrim(p_entity ->> 'fiscalAddress'),
      nullif(btrim(p_entity ->> 'grossIncomeNumber'), ''),
      nullif(btrim(p_entity ->> 'billingEmail'), ''),
      p_entity ->> 'defaultVoucher',
      coalesce((p_entity ->> 'allowsBExempt')::boolean, false),
      nullif(btrim(p_entity ->> 'pointOfSale'), ''),
      nullif(upper(btrim(p_entity ->> 'invoicePrefix')), ''),
      actor,
      actor
    ) returning * into saved_entity;
  else
    select updated_at into current_updated_at
    from public.billing_entities
    where id = entity_id
    for update;

    if not found then
      raise exception using errcode = 'P0002', message = 'ENTITY_NOT_FOUND';
    end if;
    if p_expected_updated_at is null or current_updated_at <> p_expected_updated_at then
      raise exception using errcode = '40001', message = 'ENTITY_VERSION_CONFLICT';
    end if;

    update public.billing_entities
    set name = btrim(p_entity ->> 'name'),
        status = coalesce(nullif(p_entity ->> 'status', ''), status),
        legal_type = p_entity ->> 'legalType',
        country_code = p_entity ->> 'countryCode',
        fiscal_id_type = p_entity ->> 'fiscalIdType',
        fiscal_id = btrim(p_entity ->> 'fiscalId'),
        fiscal_address = btrim(p_entity ->> 'fiscalAddress'),
        gross_income_number = nullif(btrim(p_entity ->> 'grossIncomeNumber'), ''),
        billing_email = nullif(btrim(p_entity ->> 'billingEmail'), ''),
        default_voucher = p_entity ->> 'defaultVoucher',
        allows_b_exempt = coalesce((p_entity ->> 'allowsBExempt')::boolean, false),
        point_of_sale = nullif(btrim(p_entity ->> 'pointOfSale'), ''),
        invoice_prefix = nullif(upper(btrim(p_entity ->> 'invoicePrefix')), ''),
        archived_at = case when coalesce(nullif(p_entity ->> 'status', ''), status) = 'archived' then now() else null end,
        archived_by = case when coalesce(nullif(p_entity ->> 'status', ''), status) = 'archived' then actor else null end,
        updated_by = actor
    where id = entity_id
    returning * into saved_entity;
  end if;

  update public.entity_bank_accounts
  set is_primary = false,
      updated_by = actor
  where entity_id = saved_entity.id and archived_at is null;

  update public.entity_bank_accounts existing
  set archived_at = now(),
      is_primary = false,
      updated_by = actor
  where existing.entity_id = saved_entity.id
    and existing.archived_at is null
    and not exists (
      select 1
      from jsonb_array_elements(p_accounts) supplied
      where nullif(supplied ->> 'id', '')::bigint = existing.id
    );

  for account in select value from jsonb_array_elements(p_accounts) loop
    account_id := nullif(account ->> 'id', '')::bigint;
    if account_id is null then
      insert into public.entity_bank_accounts (
        entity_id, bank_name, account_holder, currency, account_scope,
        cbu, alias, account_number, routing_number, swift_bic, iban,
        is_primary, created_by, updated_by
      ) values (
        saved_entity.id,
        btrim(account ->> 'bankName'),
        btrim(account ->> 'accountHolder'),
        upper(account ->> 'currency'),
        account ->> 'accountScope',
        nullif(regexp_replace(coalesce(account ->> 'cbu', ''), '[^0-9]', '', 'g'), ''),
        nullif(btrim(account ->> 'alias'), ''),
        nullif(btrim(account ->> 'accountNumber'), ''),
        nullif(btrim(account ->> 'routingNumber'), ''),
        nullif(upper(btrim(account ->> 'swiftBic')), ''),
        nullif(upper(btrim(account ->> 'iban')), ''),
        coalesce((account ->> 'isPrimary')::boolean, false),
        actor,
        actor
      );
    else
      update public.entity_bank_accounts
      set bank_name = btrim(account ->> 'bankName'),
          account_holder = btrim(account ->> 'accountHolder'),
          currency = upper(account ->> 'currency'),
          account_scope = account ->> 'accountScope',
          cbu = nullif(regexp_replace(coalesce(account ->> 'cbu', ''), '[^0-9]', '', 'g'), ''),
          alias = nullif(btrim(account ->> 'alias'), ''),
          account_number = nullif(btrim(account ->> 'accountNumber'), ''),
          routing_number = nullif(btrim(account ->> 'routingNumber'), ''),
          swift_bic = nullif(upper(btrim(account ->> 'swiftBic')), ''),
          iban = nullif(upper(btrim(account ->> 'iban')), ''),
          is_primary = coalesce((account ->> 'isPrimary')::boolean, false),
          archived_at = null,
          updated_by = actor
      where id = account_id and entity_id = saved_entity.id;

      if not found then
        raise exception using errcode = '22023', message = 'BANK_ACCOUNT_NOT_FOUND';
      end if;
    end if;
  end loop;

  return saved_entity;
end;
$$;

create or replace function public.set_billing_entity_status(
  p_entity_id bigint,
  p_status text,
  p_expected_updated_at timestamptz
)
returns public.billing_entities
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  current_updated_at timestamptz;
  saved_entity public.billing_entities;
begin
  if actor is null then
    raise exception using errcode = '42501', message = 'AUTH_REQUIRED';
  end if;
  if p_status not in ('active', 'inactive', 'archived') then
    raise exception using errcode = '22023', message = 'INVALID_ENTITY_STATUS';
  end if;

  select updated_at into current_updated_at
  from public.billing_entities
  where id = p_entity_id
  for update;

  if not found then
    raise exception using errcode = 'P0002', message = 'ENTITY_NOT_FOUND';
  end if;
  if current_updated_at <> p_expected_updated_at then
    raise exception using errcode = '40001', message = 'ENTITY_VERSION_CONFLICT';
  end if;

  update public.billing_entities
  set status = p_status,
      archived_at = case when p_status = 'archived' then now() else null end,
      archived_by = case when p_status = 'archived' then actor else null end,
      updated_by = actor
  where id = p_entity_id
  returning * into saved_entity;

  return saved_entity;
end;
$$;

create or replace function public.register_arca_document(
  p_entity_id bigint,
  p_original_file_name text,
  p_storage_path text,
  p_expiration_date date,
  p_uploaded_by uuid
)
returns public.entity_arca_documents
language plpgsql
security definer
set search_path = ''
as $$
declare
  entity_type text;
  entity_status text;
  saved_document public.entity_arca_documents;
begin
  if auth.role() <> 'service_role' then
    raise exception using errcode = '42501', message = 'SERVICE_ROLE_REQUIRED';
  end if;

  select legal_type, status into entity_type, entity_status
  from public.billing_entities
  where id = p_entity_id
  for update;

  if not found then
    raise exception using errcode = 'P0002', message = 'ENTITY_NOT_FOUND';
  end if;
  if entity_type = 'llc' then
    raise exception using errcode = '23514', message = 'ARCA_NOT_APPLICABLE';
  end if;
  if entity_status = 'archived' then
    raise exception using errcode = '23514', message = 'ARCHIVED_ENTITY';
  end if;

  update public.entity_arca_documents
  set superseded_at = now()
  where entity_id = p_entity_id and superseded_at is null and revoked_at is null;

  insert into public.entity_arca_documents (
    entity_id, original_file_name, storage_path, expiration_date, uploaded_by
  ) values (
    p_entity_id, btrim(p_original_file_name), p_storage_path, p_expiration_date, p_uploaded_by
  ) returning * into saved_document;

  return saved_document;
end;
$$;

create or replace function public.revoke_arca_document(
  p_document_id bigint
)
returns public.entity_arca_documents
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  saved_document public.entity_arca_documents;
begin
  if actor is null then
    raise exception using errcode = '42501', message = 'AUTH_REQUIRED';
  end if;

  update public.entity_arca_documents
  set revoked_at = now(), revoked_by = actor
  where id = p_document_id and superseded_at is null and revoked_at is null
  returning * into saved_document;

  if not found then
    raise exception using errcode = 'P0002', message = 'CURRENT_DOCUMENT_NOT_FOUND';
  end if;

  return saved_document;
end;
$$;

alter table public.profiles enable row level security;
alter table public.billing_entities enable row level security;
alter table public.entity_bank_accounts enable row level security;
alter table public.entity_arca_documents enable row level security;

revoke all on table public.profiles from anon, authenticated;
revoke all on table public.billing_entities from anon, authenticated;
revoke all on table public.entity_bank_accounts from anon, authenticated;
revoke all on table public.entity_arca_documents from anon, authenticated;

grant select on table public.profiles to authenticated;
grant select on table public.billing_entities to authenticated;
grant select on table public.entity_bank_accounts to authenticated;
grant select on table public.entity_arca_documents to authenticated;

create policy "Authenticated users read profiles"
on public.profiles for select to authenticated using (true);

create policy "Authenticated users read billing entities"
on public.billing_entities for select to authenticated using (true);

create policy "Authenticated users read entity bank accounts"
on public.entity_bank_accounts for select to authenticated using (true);

create policy "Authenticated users read ARCA document metadata"
on public.entity_arca_documents for select to authenticated using (true);

revoke execute on function public.save_billing_entity(jsonb, jsonb, timestamptz) from public, anon;
revoke execute on function public.set_billing_entity_status(bigint, text, timestamptz) from public, anon;
revoke execute on function public.register_arca_document(bigint, text, text, date, uuid) from public, anon, authenticated;
revoke execute on function public.revoke_arca_document(bigint) from public, anon;

grant execute on function public.save_billing_entity(jsonb, jsonb, timestamptz) to authenticated;
grant execute on function public.set_billing_entity_status(bigint, text, timestamptz) to authenticated;
grant execute on function public.register_arca_document(bigint, text, text, date, uuid) to service_role;
grant execute on function public.revoke_arca_document(bigint) to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('arca-documents', 'arca-documents', false, 10485760, array['application/pdf'])
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create policy "Authenticated users read ARCA files"
on storage.objects for select to authenticated
using (bucket_id = 'arca-documents');